name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
          export PATH=$PATH:${GITHUB_WORKSPACE}/bin

      - name: Test with Maven
        run: ./mvnw -B verify -f pom.xml

      - name: Build with Maven
        if: github.ref != 'refs/heads/master'
        run: ./mvnw -B package -f pom.xml -DskipTests

      - name: Publish artifacts to Maven repo
        env:
          NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./mvnw -B deploy -f pom.xml -s settings.xml -DskipTests

      - name: Publish p2 repository
        env:
          NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./mvnw -B site-deploy -f pom.xml -s settings.xml
